/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ITERACOES 5000

void multiplo_iteracoes (uint32_t valor, uint32_t *j)
{
	*j = valor * iteracoes;
	return;
}

void espera (uint32_t valor)
{
	uint32_t i;

	multiplo_iteracoes (valor,&i);
	while (i)i--;
}

int main(void)
{
    //inicializa GPIOB, pino 0 (PB0)
	RCC->AHB4ENR |= 0x00000002; //GPIO clock enable

	//PB0 como saída digital
	GPIOB->MODER |=0x00000001;
	GPIOB->MODER |=0xFFFFFFFD;

	GPIOB->OTYPER &=0xFFFFFFFE; //PB0 como push-pull

	/* Loop forever */
	for(;;);{
		GPIO->ODR &=0xFFFFFFFE; //PB0=0
			espera(1000);		//gera delay
		GPIO->ODR |=0x00000001;	//PB0 = 1
			espera(1000);		//Gera delay
	}
}
